---

stages:
  - build
  - trigger

image: docker.io/library/docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - echo "$DOCKER_TOKEN" |
    docker login docker.io -u $DOCKER_USER --password-stdin
  - echo "$GITLAB_TOKEN" |
    docker login registry.gitlab.com -u $GITLAB_USER --password-stdin

build:7.2:
  stage: build
  script:
    - cd 7.2
    - docker build -t
      registry.gitlab.com/dockerwest/image/php:7.2 .
    - docker tag registry.gitlab.com/dockerwest/image/php:7.2
      docker.io/dockerwest/php:7.2
    - docker push registry.gitlab.com/dockerwest/image/php:7.2
    - docker push docker.io/dockerwest/php:7.2
  only:
    - main

build:7.3:
  stage: build
  script:
    - cd 7.3
    - docker build -t
      registry.gitlab.com/dockerwest/image/php:7.3 .
    - docker tag registry.gitlab.com/dockerwest/image/php:7.3
      docker.io/dockerwest/php:7.3
    - docker push registry.gitlab.com/dockerwest/image/php:7.3
    - docker push docker.io/dockerwest/php:7.3
  only:
    - main

build:7.4:
  stage: build
  script:
    - cd 7.4
    - docker build -t
      registry.gitlab.com/dockerwest/image/php:7.4 .
    - docker tag registry.gitlab.com/dockerwest/image/php:7.4
      docker.io/dockerwest/php:7.4
    - docker push registry.gitlab.com/dockerwest/image/php:7.4
    - docker push docker.io/dockerwest/php:7.4
  only:
    - main

build:8.0:
  stage: build
  script:
    - cd 8.0
    - docker build -t
      registry.gitlab.com/dockerwest/image/php:8.0 .
    - docker tag registry.gitlab.com/dockerwest/image/php:8.0
      docker.io/dockerwest/php:8.0
    - docker push registry.gitlab.com/dockerwest/image/php:8.0
    - docker push docker.io/dockerwest/php:8.0
  only:
    - main

build:8.1:
  stage: build
  script:
    - cd 8.1
    - docker build -t
      registry.gitlab.com/dockerwest/image/php:8.1 .
    - docker tag registry.gitlab.com/dockerwest/image/php:8.1
      docker.io/dockerwest/php:8.1
    - docker push registry.gitlab.com/dockerwest/image/php:8.1
    - docker push docker.io/dockerwest/php:8.1
  only:
    - main

#trigger:php-laravel:
  #stage: trigger
  #trigger:
    #project: DockerWest/image/php-laravel

#trigger:php-magento1:
  #stage: trigger
  #trigger:
    #project: DockerWest/image/php-magento1

#trigger:php-magento2:
  #stage: trigger
  #trigger:
    #project: DockerWest/image/php-magento2

#trigger:php-pimcore:
  #stage: trigger
  #trigger:
    #project: DockerWest/image/php-pimcore

#trigger:php-symfony:
  #stage: trigger
  #trigger:
    #project: DockerWest/image/php-symfony

#trigger:php-sylius:
  #stage: trigger
  #trigger:
    #project: DockerWest/image/php-sylius

#trigger:php-wordpress:
  #stage: trigger
  #trigger:
    #project: DockerWest/image/php-wordpress
